# rumqttd embedded broker configuration
id = 0

[router]
max_connections = 100
max_outgoing_packet_count = 200
max_segment_size = 1048576
max_segment_count = 10

[v4.1]
name = "v4-1"
listen = "0.0.0.0:1883"
next_connection_delay_ms = 1
    [v4.1.connections]
    connection_timeout_ms = 60000
    max_payload_size = 20480
    max_inflight_count = 100
    dynamic_filters = true

